spring:
  main:
    web-application-type: none
    banner-mode: off

  datasource:
    datasource-mart:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres

    datasource-sqlite:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:test.db
      
